cluster:
  name: ${CLUSTER_NAME}
  initial_master_nodes: ${INITIAL_MASTER_NODES}

node:
  name: ${NODE_NAME}

network.host: 0.0.0.0

path:
  data: /data/data
  logs: /data/log

bootstrap:
  memory_lock: false

http:
  compression: true
  cors:
    enabled: ${HTTP_CORS_ENABLE}
    allow-origin: ${HTTP_CORS_ALLOW_ORIGIN}
    allow-credentials: true
    allow-headers: "X-Requested-With, Content-Type, Content-Length, Authorization"

discovery.seed_hosts: ${DISCOVERY_SERVICE}

xpack.security.enabled: ${XPACK_SECURITY_ENABLED:false}
